# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosoo < Formula
  desc "Generated CLI for Mosoo integrators"
  homepage "https://github.com/langgenius/mosoo-connector"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.2/mosoo-darwin-amd64.tar.gz"
      sha256 "c9cf7be1e0850c232b7e10e1ca596eb8177881bb7d5391988f0b03caba5c56bb"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.2/mosoo-darwin-arm64.tar.gz"
      sha256 "34e91186d2de591b45970c4e4592436e2762ef1b2461ef58b5d9d5bc9123f155"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.2/mosoo-linux-amd64.tar.gz"
      sha256 "2b9b669d74c2d9dc2b7a0be5f5b2e1912e897503bfbfae7aaaa2b4c17f9181c6"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.1.2/mosoo-linux-arm64.tar.gz"
      sha256 "1fe2390e5938b3fa32d763bf88e60eb135ffdf50d563c27befe0970c2a0cf133"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  test do
    assert_match "mosoo v0.1.2", shell_output("#{bin}/mosoo --version")
    system "#{bin}/mosoo", "commands", "--json"
  end
end
