# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosoo < Formula
  desc "Generated CLI for mosoo integrators"
  homepage "https://github.com/langgenius/mosoo-connector"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.2.0/mosoo-darwin-amd64.tar.gz"
      sha256 "1bcc0ecd4c35147ea1669ba91712f2118584d2454eed09711785af38875da448"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.2.0/mosoo-darwin-arm64.tar.gz"
      sha256 "81b1e70a268c72fc7308dd95397bc2efad37e5d2aa7ff50a8cb6981486262d64"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.2.0/mosoo-linux-amd64.tar.gz"
      sha256 "c568d976cac6c0af229f0a19afe2b9a2ba1c4aa6477ec42fb8b9f27ad7774620"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.2.0/mosoo-linux-arm64.tar.gz"
      sha256 "ad14341bdecd06b9d2bc94bbcd4fc74496f7e4d82bc0fb78ca0ef547f878bcbe"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  test do
    assert_match "mosoo v0.2.0", shell_output("#{bin}/mosoo --version")
    system "#{bin}/mosoo", "commands", "--json"
  end
end
