# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mosoo < Formula
  desc "Generated CLI for mosoo integrators"
  homepage "https://github.com/langgenius/mosoo-connector"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.7.0/mosoo-darwin-amd64.tar.gz"
      sha256 "10727a3f51c952fc427aa6b905fd5fa60353aac7a16e195d30839f37fee147dc"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.7.0/mosoo-darwin-arm64.tar.gz"
      sha256 "8be74e204d7084a8c667e5259652697657e91b5338f5b28d72b47690ce6d6613"

      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.7.0/mosoo-linux-amd64.tar.gz"
      sha256 "28e23dd9cf3b37a1ef892d6d7b4ae1c75aa02a6d80ee4521cf9adb2988faa355"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/mosoo-connector/releases/download/v0.7.0/mosoo-linux-arm64.tar.gz"
      sha256 "616b5dcfce0d6407c4e46057a121a3e76ff6c7b53f079d80e899cf27686f3610"
      define_method(:install) do
        bin.install "mosoo"
      end
    end
  end

  test do
    assert_match "mosoo v0.7.0", shell_output("#{bin}/mosoo --version")
    system "#{bin}/mosoo", "commands", "--json"
  end
end
